### ISSUE TITLE
i like your work

### ISSUE THREAD

**Issue by birdlip** [Moritz0203/EFT-Bot#1]
what is your discord?

**Comment by Moritz0203** [comment]
Sorry I'm so late answering here is my username: "moritz0203" and glad you like what I do. 
Please tell me when you add me it could be that I don't see it so feel free to write me your Discord name as well.

**Comment by birdlip** [comment]
I just saw your message I will add you when I get home

**Comment by Moritz0203** [comment]
Do that then just let me know again so I know it's you

**Comment by birdlip** [comment]
just sent

**Comment by Moritz0203** [comment]
I have accepted you
